steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/kazilog-dev/kazilog', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/kazilog-dev/kazilog']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'kazilog-service', '--image', 'gcr.io/kazilog-dev/kazilog', '--region', 'asia-northeast1']
images:
- gcr.io/kazilog-dev/kazilog