query kazisToday {
  kazisToday {
    id
    category {
      id
      name
    }
    name
    point
    repeat {
      type
      activatedAt
    }
    user {
      uid
      name
    }
    doneAt
    memo
  }
}
